[project]
name = "141xp-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=3.0.4",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "plotly>=6.1.2",
]
